// <auto-generated />
using System;
using FsEngineeringTest1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FsEngineeringTest1.Migrations
{
    [DbContext(typeof(ChuckDBContext))]
    partial class ChuckDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FsEngineeringTest1.Models.Categories", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"), 1L, 1);

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FsEngineeringTest1.Models.Jokes", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("created")
                        .HasColumnType("DateTime");

                    b.Property<string>("icon_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("DateTime");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MaxLength)");

                    b.HasKey("id");

                    b.ToTable("Jokes");
                });

            modelBuilder.Entity("FsEngineeringTest1.Models.People", b =>
                {
                    b.Property<int>("peopleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("peopleId"), 1L, 1);

                    b.Property<string>("birth_year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("edited")
                        .HasColumnType("DateTime");

                    b.Property<string>("eye_color")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("hair_color")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("height")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("homeworld")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<double>("mass")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("skin_color")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("peopleId");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
